In [2]:
# 1. Dadas 2 matrices con dimensiones similares, ¿cómo obtener una salida de matriz en la que cada elemento es una suma de elementos de las 2
# matrices? (solo puede usar numpy como librería, si realiza la matriz con otro paquete el ejercicio no es válido)

import numpy as np

# Matriz 1
matriz_1 = np.array([[1, 3, 5], [7, 9, 11], [13, 15, 17]])

# Matriz 2
matriz_2 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])

# Matriz de salida
matriz_salida = matriz_1 + matriz_2

print(matriz_salida)


[[ 3  7 11]
 [15 19 23]
 [27 31 35]]


In [4]:
# 2 Cree una matriz de identidad de dimensión 4.

# Matriz de identidad
matriz_identidad = np.identity(4)

print(matriz_identidad)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
# 3. Convierte una matriz numpy binaria (que contiene solo 0 y 1) en una matriz numpy booleana.

# Matriz binaria
matriz_binaria = np.array([[0, 1, 0, 1], [1, 0, 1, 0], [0, 1, 0, 1]])

# Matriz booleana
matriz_booleana = matriz_binaria.astype(bool)

print(matriz_booleana)


[[False  True False  True]
 [ True False  True False]
 [False  True False  True]]


In [7]:
# 4. Genere una secuencia de números en forma de matriz numpy de 0 a 100 con espacios de 2 números, por ejemplo: 0, 2, 4 ...

# Matriz de secuencia
matriz_secuencia = np.arange(0, 100, 2)

print(matriz_secuencia)



[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [24]:
# ¿Qué es la librería numpy?
# Es una librería de Python que nos permite realizar operaciones matemáticas y estadísticas sobre matrices y vectores.

# ¿Conocemos los términos de vectores y matrices?
# Un vector es una lista de números, mientras que una matriz es una lista de vectores.
