PARTE 1

In [1]:
# Parte 1

# 1. La principal diferencia entre los métodos supervisados (I) y no supervisados (II) es que:

#R:  c) (I) usan la variable respuesta para entrenar el modelo.

# 2. Considere las siguientes afirmaciones:
# (i) PCA es un método no supervisado.
# (ii) Todos los componentes principales de un PCA son ortogonales entre si.
# (iii) PCA busca las direcciones en las que los datos tienen la mayor varianza.
# (iv) El número máximo de componentes principales es menor o igual al número de variables.

# Elija la opción con el mayor número de ítems correctos:
# R: a) (i) e (iii).

# 3. Como parte de un análisis de datos se analizaron 11 indicadores económicos y sociales de 96
# países. 

# R: d) No es posible interpretar los resultados anteriores debido a que es un error haber utilizado
# la matriz de correlación y en su lugar se debería haber utilizado la matriz de covarianzas.


In [2]:
# 4. Considere las siguientes observaciones:

# i 1 2 3 4 5 6 7 8
# Xi 10 8 34 9 46 68 80 50
# Yi 4 99 44 50 77 30 25 35
# Zi 50 31 86 57 75 14 40 60

# Sin escalar las variables, describa tres iteraciones del algoritmo K-means para k = 2. Use los
# centroides C1 = (47.5, 37.5, 21.8) y C2 = (53.2, 22.4, 75.3).

# Observación: El objetivo del ejercicio es saber si comprenden cómo funcionan internamente el
# algoritmo, así que no basta con sólo la respuesta en Python u otro lenguaje. Aunque sí se
# pueden apoyar en algún software para los cálculos de cada paso.

# 5. Enuncie al menos tres diferencias entre el análisis factorial y el método de componentes
# principales.



In [3]:
import numpy as np

#Set Data
x = [10,8,34,9,46,68,80,50]
y = [4,99,44,50,77,30,25,35]
z = [50,31,86,57,75,14,40,60]

data = np.array(list(zip(x, y, z)))

c1 = np.array([47.5,37.5,21.8])
c2 = np.array([53.2,22.4,75.3])

centroides = np.array([c1,c2])

In [4]:
# IT:1
#Cálculo distancia euclidiana

def euclidean_distance(punto, centroide):
    return np.sqrt(np.sum((punto - centroide)**2))

distancias = []
puntos = []
for punto in data:
    distance = [euclidean_distance(punto, centroide) for centroide in centroides]
    punto = punto
    distancias.append(distance)
    puntos.append(punto)

# Asignar centroide

clusters = [[] for _ in range(len(centroides))]

for i in range(len(puntos)):
    distancia = distancias[i]
    punto = puntos[i]
    centroide_asignado = np.argmin(distancia)
    clusters[centroide_asignado].append(punto)

for i, cluster in enumerate(clusters):
    print(f"Centroide {i+1}: {cluster}")

#Cálculo de nuevos centroides
new_centroids = []

for cluster in clusters:
    new_centroid = np.mean(cluster, axis=0)
    new_centroids.append(new_centroid)
        
# Imprimir nuevos centroides
for i, centroid in enumerate(new_centroids):
    print(f"Nuevo centroide {i+1}: {centroid}")


Centroide 1: [array([ 8, 99, 31]), array([ 9, 50, 57]), array([68, 30, 14]), array([80, 25, 40])]
Centroide 2: [array([10,  4, 50]), array([34, 44, 86]), array([46, 77, 75]), array([50, 35, 60])]
Nuevo centroide 1: [41.25 51.   35.5 ]
Nuevo centroide 2: [35.   40.   67.75]


In [5]:
#IT#2
#Cálculo distancia euclidiana

distancias = []
puntos = []
for punto in data:
    distance = [euclidean_distance(punto, centroide) for centroide in new_centroids]
    punto = punto
    distancias.append(distance)
    puntos.append(punto)

# Asignar centroide

clusters_2 = [[] for _ in range(len(new_centroids))]

for i in range(len(puntos)):
    distancia = distancias[i]
    punto = puntos[i]
    centroide_asignado = np.argmin(distancia)
    clusters_2[centroide_asignado].append(punto)

for i, cluster in enumerate(clusters_2):
    print(f"Centroide {i+1}: {cluster}")

#Cálculo de nuevos centroides
new_centroids2 = []

for cluster in clusters_2:
    new_centroid2 = np.mean(cluster, axis=0)
    new_centroids2.append(new_centroid2)
        
# Imprimir nuevos centroides
for i, centroid in enumerate(new_centroids2):
    print(f"Nuevo centroide {i+1}: {centroid}")


Centroide 1: [array([ 8, 99, 31]), array([68, 30, 14]), array([80, 25, 40])]
Centroide 2: [array([10,  4, 50]), array([34, 44, 86]), array([ 9, 50, 57]), array([46, 77, 75]), array([50, 35, 60])]
Nuevo centroide 1: [52.         51.33333333 28.33333333]
Nuevo centroide 2: [29.8 42.  65.6]


In [6]:
# IT#3
#Iteración 3
#Cálculo distancia euclidiana

distancias = []
puntos = []
for punto in data:
    distance = [euclidean_distance(punto, centroide) for centroide in new_centroids2]
    punto = punto
    distancias.append(distance)
    puntos.append(punto)

# Asignar cada punto a un centroide

clusters_3 = [[] for _ in range(len(new_centroids2))]

for i in range(len(puntos)):
    distancia = distancias[i]
    punto = puntos[i]
    centroide_asignado = np.argmin(distancia)
    clusters_3[centroide_asignado].append(punto)

for i, cluster in enumerate(clusters_3):
    print(f"Centroide {i+1}: {cluster}")

#Cálculo de nuevos centroides
new_centroids3 = []

for cluster in clusters_3:
    new_centroid3 = np.mean(cluster, axis=0)
    new_centroids3.append(new_centroid3)
        
# Imprimir nuevos centroides
for i, centroid in enumerate(new_centroids3):
    print(f"Nuevo centroide {i+1}: {centroid}")

print("Puntos asignados a cada centroide:")
for i, cluster in enumerate(clusters_3):
    print(f"Cluster {i+1}:")
    for point in cluster:
        print(point)

Centroide 1: [array([ 8, 99, 31]), array([68, 30, 14]), array([80, 25, 40])]
Centroide 2: [array([10,  4, 50]), array([34, 44, 86]), array([ 9, 50, 57]), array([46, 77, 75]), array([50, 35, 60])]
Nuevo centroide 1: [52.         51.33333333 28.33333333]
Nuevo centroide 2: [29.8 42.  65.6]
Puntos asignados a cada centroide:
Cluster 1:
[ 8 99 31]
[68 30 14]
[80 25 40]
Cluster 2:
[10  4 50]
[34 44 86]
[ 9 50 57]
[46 77 75]
[50 35 60]


In [7]:
# 5. Enuncie al menos tres diferencias entre el análisis factorial y el método de componentes
# principales.

# 1. El análisis factorial busca identificar variables latentes y PAC busca construir nuevas variables no correlacionadas, representando los datos en un espacio de menor dimensión.
# 2. El análisis factorial asume una relación lineal entre las variables latentes y las observadas. En el caso del PAC no asume ninguna relación.
# 3. El análisis factorial requiere que los datos sean cuantitativos u ordinales, en el caso del PAC recibe distintos tipos de datos.


In [8]:
# 6. ¿Qué significa que el método de clusterización sea jerárquico?

# Significa que los clusters se van formando de manera jerárquica, es decir, se van formando clusters de clusters.
